### ISSUE TITLE
Build Error in School_Meal.Android

### ISSUE THREAD

**Issue by ksjae** [sboh1214/School_Meal#4]
**Description :**
Build Error

**To Reproduce**
Error occurs when building, in School_Meal.android

**Expected behavior**
Gets Built, obviously

**Erro r Message**
/Users/sjk/Documents/GitHub/School_Meal/School_Meal_Mobile/School_Meal_Mobile.Android/Resources/values/styles.xml(0,0): Error APT0000: Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.DarkActionBar'. (APT0000) (School_Meal_Mobile.Android)
/Users/sjk/Documents/GitHub/School_Meal/School_Meal_Mobile/School_Meal_Mobile.Android/Resources/values/styles.xml(0,0): Error APT0000: No resource found that matches the given name: attr 'colorAccent'. (APT0000) (School_Meal_Mobile.Android)
/Users/sjk/Documents/GitHub/School_Meal/School_Meal_Mobile/School_Meal_Mobile.Android/Resources/values/styles.xml(0,0): Error APT0000: No resource found that matches the given name: attr 'colorPrimary'. (APT0000) (School_Meal_Mobile.Android)
/Users/sjk/Documents/GitHub/School_Meal/School_Meal_Mobile/School_Meal_Mobile.Android/Resources/values/styles.xml(0,0): Error APT0000: No resource found that matches the given name: attr 'colorPrimaryDark'. (APT0000) (School_Meal_Mobile.Android)
/Users/sjk/Documents/GitHub/School_Meal/School_Meal_Mobile/School_Meal_Mobile.Android/Resources/values/styles.xml(0,0): Error APT0000: No resource found that matches the given name: attr 'windowActionBar'. (APT0000) (School_Meal_Mobile.Android)
/Users/sjk/Documents/GitHub/School_Meal/School_Meal_Mobile/School_Meal_Mobile.Android/Resources/values/styles.xml(0,0): Error APT0000: No resource found that matches the given name: attr 'windowActionModeOverlay'. (APT0000) (School_Meal_Mobile.Android)
/Users/sjk/Documents/GitHub/School_Meal/School_Meal_Mobile/School_Meal_Mobile.Android/Resources/values/styles.xml(0,0): Error APT0000: No resource found that matches the given name: attr 'windowNoTitle'. (APT0000) (School_Meal_Mobile.Android)
/Users/sjk/Documents/GitHub/School_Meal/School_Meal_Mobile/School_Meal_Mobile.Android/Resources/values/styles.xml(0,0): Error APT0000: Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.Dialog'. (APT0000) (School_Meal_Mobile.Android)
/Users/sjk/Documents/GitHub/School_Meal/School_Meal_Mobile/School_Meal_Mobile.Android/Resources/values/styles.xml(0,0): Error APT0000: No resource found that matches the given name: attr 'colorAccent'. (APT0000) (School_Meal_Mobile.Android)

**Device (please complete the following information):**
 - OS: Mac OS X High Sierra
 - OS Version : 10.13.5
 - App Version : 0.1
 

**Additional context**

**Comment by sboh1214** [comment]
Plz check master branch one more time
now i'm merged develop branch to master branch
